volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  bitrixdock:

services:
  php:
    build: ./services/php/${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}.php
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
    restart: unless-stopped
  web_server:
    build: ./services/web_server/${WEB_SERVER_TYPE}
    container_name: ${COMPOSE_PROJECT_NAME}.web_server
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:${PORT_WEB_SERVER_HTTP}:80'
      - '${INTERFACE}:${PORT_WEB_SERVER_HTTPS}:443'
    links:
      - php
    networks:
      - bitrixdock
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  db:
    build: ./services/db/${DB_SERVER_TYPE}
    container_name: ${COMPOSE_PROJECT_NAME}.db
    volumes:
      - ./services/db/${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:${PORT_DB}:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Moscow
    command: mysqld --user=root --sql-mode=""
    networks:
      - bitrixdock
    stdin_open: true
    tty: true
    restart: unless-stopped
  memcached:
    image: memcached:latest
    container_name: ${COMPOSE_PROJECT_NAME}.memcached
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:${PORT_MEMCACHED}:11211'
    networks:
      - bitrixdock
    environment:
      - TZ=Europe/Moscow
    stdin_open: true
    tty: true
    restart: unless-stopped
  adminer:
    image: dockette/adminer:full
    container_name: ${COMPOSE_PROJECT_NAME}.adminer
    links:
      - db:db
    ports:
      - '${INTERFACE}:${PORT_ADMINER}:80'
    environment:
      UPLOAD: 1024M # upload_max_filesize, post_max_size
      TZ: Europe/Moscow
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - bitrixdock
  source:
    image: alpine:latest
    container_name: ${COMPOSE_PROJECT_NAME}.source
    volumes:
      - ./data/logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
      - ./data/logs/php:/var/log/php
      - ./data/logs/db:/var/log/mysql
      - ./data/logs/memcached:/var/log/memcached
      - ./data/db:/var/lib/mysql
      - ./data/cache:/var/lib/memcached
      - ${SITE_PATH}:/var/www/bitrix
      - /etc/localtime:/etc/localtime/:ro
    networks:
      - bitrixdock
